# Generated by Django 6.0.5 on 2026-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10, null=True)),
                ('ml_prediction', models.IntegerField(default=0)),
                ('ml_confidence', models.FloatField(default=0.0)),
                ('ml_model_used', models.CharField(default='RandomForest', max_length=50)),
                ('snort_alert', models.BooleanField(default=False)),
                ('snort_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('decision', models.CharField(choices=[('BENIGN', 'Benign'), ('ALERT', 'Alert'), ('THREAT', 'Threat')], default='BENIGN', max_length=10)),
                ('source_tag', models.CharField(choices=[('ML_ONLY', 'ML Only'), ('SNORT_ONLY', 'Snort Only'), ('BOTH', 'Both'), ('NONE', 'None')], default='NONE', max_length=15)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
