# Generated by Django 6.0.5 on 2026-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='attack_type',
            field=models.CharField(default='BENIGN', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='detection_mode',
            field=models.CharField(default='binary', max_length=15),
        ),
    ]
